name: hprofile Action
on: workflow_dispatch 
jobs:
  Testing:
    runs-on: ubuntu-latest 
    steps:
      - name: git checkout step 
        uses: actions/checkout@v4
      
      - name: Maven test
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle
        
